# ----------------------------------------------------- #
# A Snakemake workflow for the post-processing of       #
# microbial genome assemblies.                          #
# ----------------------------------------------------- #

import os
from datetime import datetime


# -----------------------------------------------------
# container definition (optional)
# -----------------------------------------------------
container: "oras://ghcr.io/mpusp/snakemake-assembly-postprocessing:latest"


# -----------------------------------------------------
# load configuration
# -----------------------------------------------------
configfile: "config/config.yml"


# -----------------------------------------------------
# load rules
# -----------------------------------------------------
include: "rules/common.smk"
include: "rules/annotate.smk"


# -----------------------------------------------------
# meta data and run info
# -----------------------------------------------------
__authors__ = ["Rina Ahmed-Begrich", "Michael Jahn"]

cyan = "\033[36m"
end = "\033[0m"

msg = f"""\nSnakemake-assembly-postprocessing: A Snakemake workflow 
for the post-processing of microbial genome assemblies."""

prolog = f"Output directory: ./results"
year = datetime.today().year

epilog = f"""
Written by {", ".join(__authors__)}.
Max Planck Unit for the Science of Pathogens. Copyright (c) {year}.
"""


# -----------------------------------------------------
# optional messages, log and error handling
# -----------------------------------------------------
onstart:
    print(f"{cyan}\n--- Workflow started! ---\n\n{prolog}\n\n{end}")


onsuccess:
    print(f"{cyan}\n{msg}\n{epilog}\n--- Workflow finished! ---\n\n{end}")


onerror:
    print(f"{cyan}\n{msg}\n{epilog}\n --- An error occurred! ---\n\n{end}")


# -----------------------------------------------------
# target rules
# -----------------------------------------------------
rule all:
    input:
        expand(
            "results/annotation/{tool}/{sample}/{sample}.gff",
            tool=config["tool"],
            sample=samples.index,
        ),
    default_target: True
