$schema: "https://json-schema.org/draft/2020-12/schema"
description: Schema for the configuration file of the assembly post-processing workflow
type: object
properties:
  samplesheet:
    type: string
    description: Path to the sample sheet file

required:
- samplesheet
