samplesheet: "config/samples.csv"
tool: ["prokka"]

reference:
  fasta: ""
  gff: ""

pgap:
  bin: "path/to/pgap.py"
  use_yaml_config: True
  prepare_yaml_files:
    generic: "config/generic.yaml"
    submol: "config/submol.yaml"

prokka:
  center: ""
  extra: "--addgenes"

bakta:
  download_db: "light"
  existing_db: ""
  extra: "--keep-contig-headers --compliant"

quast:
  extra: ""

panaroo:
  skip: False
  remove_source: "cmsearch"
  remove_feature: "tRNA|rRNA|ncRNA|exon|sequence_feature"
  extra: "--clean-mode strict --remove-invalid-genes"

fastani:
  skip: False
  extra: ""

rgi:
  skip: False
  extra: "--clean --alignment_tool DIAMOND"

synteny:
  skip: False
  divergence: 1 # maximum divergence range between genome (default: 1)
  prefix: "ntSynt"
  extra: ""
  viz_scale: "1e6"
  viz_extra: "--normalize --format pdf"
