samplesheet: "config/samples.csv"
outdir: "results"
tool: "prokka"

pgap:
  bin: "path/to/pgap.py"
  use_yaml_config: True
  prepare_yaml_files:
    generic: "config/generic.yaml"
    submol: "config/submol.yaml"

prokka:
  center: ""
  extra: "--addgenes"
