samplesheet: "config/samples.csv"
tool: ["prokka"]

pgap:
  bin: "path/to/pgap.py"
  use_yaml_config: True
  prepare_yaml_files:
    generic: "config/generic.yaml"
    submol: "config/submol.yaml"

prokka:
  center: ""
  extra: "--addgenes"

bakta:
  download_db: "light"
  existing_db: ""
  extra: "--keep-contig-headers --compliant"

quast:
  reference: ""
  extra: ""
